sudo: required

services:
  - docker

before_install:
  - docker info
  - docker version

  - docker build -t ansible-recipe .

script:
  - docker run -i ansible-recipe > result
  - echo "===> Validating the test results..."
  - sh -c "[ -s result ]"
