---
  - name: get kapacitor rpm
    get_url: >
            url="https://dl.influxdata.com/kapacitor/releases/kapacitor-{{kapacitor_version}}.{{kapacitor_arch}}.rpm"
            dest="{{home}}/kapacitor-{{kapacitor_version}}.{{kapacitor_arch}}.rpm"
    tags:
      - kapacitor-get-rpm
  - name: install kapacitor
    yum: name="{{home}}/kapacitor-{{kapacitor_version}}.{{kapacitor_arch}}.rpm" state=present
    tags:
      - kapacitor-install
  - name: start kapacitor
    service: name=kapacitor state=started
    tags:
      - kapacitor-start
  - name: stop kapacitor
    service: name=kapacitor state=stopped
    tags:
      - kapacitor-stop
  - name: erase kapacitor
    yum: name=kapacitor state=absent
    tags:
      - kapacitor-erase
  - name: enable kapacitor
    service: name=kapacitor enabled=true
    tags:
      - kapacitor-enable
