---
  - name: install influxdb
    yum: name="https://dl.influxdata.com/influxdb/releases/influxdb-{{influxdb_version}}.{{influxdb_arch}}.rpm" dest="~/influxdb-{{influxdb_version}}.{{influxdb_arch}}.rpm" state=present
    tags:
      - influxdb-install
  - name: erase influxdb
    yum: name=influxdb state=absent
    tags:
      - influxdb-erase
  - name: start influxdb
    service: name=influxdb state=started
    tags:
      - influxdb-start
  - name: stop influxdb
    service: name=influxdb state=stopped
    tags:
      - influxdb-stop
  - name: enable influxdb
    service: name=influxdb enabled=true
    tags:
      - influxdb-enable
