---
  - name: get nsq archive file
    get_url: >
            url="https://s3.amazonaws.com/bitly-downloads/nsq/nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}.tar.gz"
            dest="{{nsq_home}}/nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}.tar.gz"
  - name: extract "nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}.tar.gz"
    command: /usr/bin/which tar -C /usr/local -xzf "{{nsq_home}}/nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}.tar.gz"
    args:
      creates: "/usr/local/nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}/.ar"
  - name: export "nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}/bin"
    command: export PATH=$PATH:"/usr/local/nsq-{{nsq_version}}.{{nsq_os}}-{{nsq_arch}}.go{{nsq_go_version}}/bin"
